apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: tienda
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: tienda
  MYSQL_USER: admin
  MYSQL_PASSWORD: admin123
